intro/hello/urls.py
from django.urls import path

from hello import views


urlpatterns = [
    path('home/', views.home),
    path('adam/', views.adam),
    path('ewa/', views.ewa),
    path('greet/', views.greet),

    path('isitmonday/', views.is_monday),
    path('fruits/', views.show_fruits),

    path('<name>/', views.hello),
    path('2/<name>/', views.hello2),
]

intro/intro/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('inherit/', include('inheritance.urls')),
    path('links/', include('links.urls')),
    path('form/', include('formapp.urls')),
    path('form2/', include('formapp2.urls')),
    path('form3/', include('formapp3.urls')),
    path('form4/', include('formapp4.urls')),
    path('relation/', include('relationapp.urls')),
    path('task/', include('taskapp.urls')),
    path('forms/', include('formsapp.urls')),
    path('views/', include('viewsapp.urls')),
    path('state/', include('stateapp.urls')),
    path('auth/', include('authapp.urls')),
]

intro/links/urls.py
from django.urls import path

from links import views

app_name = 'links'

urlpatterns = [
    path('first/', views.first, name='first'),
    path('second/', views.second, name='second'),
    path('third/<str:param>/', views.third, name='third')
]

intro/links/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(
        request,
        'links/first.html'
    )


def second(request):
    return render(
        request,
        'links/second.html'
    )


def third(request, param):
    return render(
        request,
        'links/third.html',
        context={
            'param': param,
        }
    )

intro/links/templates/links/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h2>To jest pierwsza strona</h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias amet autem corporis dolore iste maiores nam optio, provident quidem quis ratione repellendus sed sequi sunt, tempora tenetur totam voluptatum.

  <p>
      Przejdź do strony <a href="{% url 'links:second' %}"> drugiej</a>
  </p>
</body>
</html>

intro/links/templates/links/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h2>To jest druga strona</h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab atque error fugiat optio? Dolorem quibusdam sit soluta? Enim harum ipsum, laudantium maxime nobis odit praesentium quaerat repellat saepe, vitae voluptas!

  <p>
      Przejdź do strony <a href="{% url 'links:third' 'abc' %}">trzeciej</a>
  </p>

</body>
</html>

intro/links/templates/links/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>To jest trzecia strona z parametrem {{ param }}</h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur dicta exercitationem ipsa non nostrum optio quidem repellat tempore ullam. Aspernatur, beatae cum doloribus expedita molestiae necessitatibus nihil non porro recusandae.

    <p>
        Przejdź do strony <a href="{% url 'links:first' %}">pierwszej</a>
    </p>
</body>
</html>