intro/hello/urls.py
from django.urls import path

from hello import views


urlpatterns = [
    path('home/', views.home),
    path('adam/', views.adam),
    path('ewa/', views.ewa),
    path('greet/', views.greet),

    path('isitmonday/', views.is_monday),
    path('fruits/', views.show_fruits),

    path('<name>/', views.hello),
    path('2/<name>/', views.hello2),
]

intro/intro/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('inherit/', include('inheritance.urls')),
    path('links/', include('links.urls')),
    path('form/', include('formapp.urls')),
    path('form2/', include('formapp2.urls')),
    path('form3/', include('formapp3.urls')),
    path('form4/', include('formapp4.urls')),
    path('relation/', include('relationapp.urls')),
    path('task/', include('taskapp.urls')),
    path('forms/', include('formsapp.urls')),
    path('views/', include('viewsapp.urls')),
    path('state/', include('stateapp.urls')),
    path('auth/', include('authapp.urls')),
]

intro/taskapp/urls.py
from django.urls import path

from taskapp import views

app_name = 'taskapp'

urlpatterns = [
    # C
    path('create/', views.task_create_view, name='task-create-view'),

    # R
    path('', views.task_list_view, name='task-list-view'),
    path('<int:task_id>/', views.task_detail_view, name='task-detail-view'),

    # U
    path('<int:task_id>/update/', views.task_update_view, name='task-update-view'),

    # D
    path('<int:task_id>/delete/', views.task_delete_view, name='task-delete-view')
]

intro/taskapp/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=256)

intro/taskapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required

from taskapp.models import Task


@permission_required('taskapp.add_task', raise_exception=True)
def task_create_view(request):
    if request.method == "GET":
        return render(
            request,
            'taskapp/create_task.html'
        )

    if request.method == "POST":
        task = request.POST.get('task')

        if task:
            Task.objects.create(name=task)

        return redirect('taskapp:task-list-view')


def task_list_view(request):

    tasks = Task.objects.all()

    return render(
        request,
        'taskapp/tasks.html',
        context={
            'tasks': tasks,
        }
    )


def task_detail_view(request, task_id):
    task = Task.objects.get(id=task_id)

    return render(
        request,
        'taskapp/task.html',
        context={
            'task': task
        }
    )


def task_update_view(request, task_id):
    task = Task.objects.get(id=task_id)

    if request.method == "GET":
        return render(
            request,
            'taskapp/update_task.html',
            context={
                'task': task,
            }
        )

    if request.method == "POST":
        new_task = request.POST.get('task')

        if new_task:
            task.name = new_task
            task.save()

        return redirect('taskapp:task-list-view')


def task_delete_view(request, task_id):
    task = Task.objects.get(id=task_id)

    if request.method == "GET":
        return render(
            request,
            'taskapp/delete_task.html',
            context={
                'task': task,
            }
        )

    if request.method == "POST":
        task.delete()
        return redirect('taskapp:task-list-view')

intro/taskapp/templates/taskapp/create_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Widok tworzenia zadania</title>
</head>
<body>
    <h3>Dodaj nowe zadanie</h3>
    <form method="POST">{% csrf_token %}
        <input type="text" name="task">
        <input type="submit" value="Dodaj">
    </form>
</body>
</html>

intro/taskapp/templates/taskapp/delete_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Widok usuwania zadania</title>
</head>
<body>
  <h3>Czy napewno chcesz usunąć zadanie {{ task.name }}?</h3>
  <form method="POST">{% csrf_token %}
    <input type="submit" value="Potwierdź">
  </form>

  <a href="{% url 'taskapp:task-list-view' %}"><button>Anuluj</button></a>
</body>
</html>

intro/taskapp/templates/taskapp/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Widok szczegółu zadania</title>
</head>
<body>
  <h3>Zadanie numer {{ task.id }}</h3>
  {{ task.name }}
</body>
</html>

intro/taskapp/templates/taskapp/tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Widok listy zadań</title>
</head>
<body>
    <h3>Lista zadań</h3>
    <a href="{% url 'taskapp:task-create-view' %}"><button>Dodaj zadanie</button></a>
    <ul>
        {% for task in tasks %}
            <li>
                <a href="{% url 'taskapp:task-detail-view' task.id %}">{{ task.name }}</a>
                <a href="{% url 'taskapp:task-update-view' task.id %}"><button>Zmodyfikuj</button></a>
                <a href="{% url 'taskapp:task-delete-view' task.id %}"><button>Usuń</button></a>
            </li>

        {% endfor %}
    </ul>
</body>
</html>

intro/taskapp/templates/taskapp/update_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Widok modyfikacji zadania</title>
</head>
<body>
    <h3>Zmodyfikuj zadanie numer {{ task.id }}</h3>
    <form method="POST">{% csrf_token %}
        <input type="text" name="task" value="{{ task.name }}">
        <input type="submit" value="Zmodyfikuj">
    </form>
</body>
</html>